### PR TITLE
Update App.config

### PR DESCRIPTION
**Pull request by rnagpal**
@mimig1 @arramac : Please review.

### CODE REVIEW

**Comment by arramac** [comment]
Looks good. @rnagpal, you should feel free to add us as FYI and merge changes like these.

**Comment by rnagpal** [comment]
@arramac Sorry. I just copy pasted this from other description as I was dynamically creating fork in the Github UI itself and hence this was sent as a separate PR. I've forked/cloned the repo on my machine now.

Also, I don't seem to have permissions to merge changes to Azure-Samples. Do you know what permissions I need or can add me to it?

**Comment by mimig1** [comment]
@rnagpal - Instructions for perms are here http://acomdocs.azurewebsites.net/articles/samples-create-new/. I think you need to be added to the team acct for the repo.

**Comment by mimig1** [comment]
@rnagpal - Correction, go to https://repos.opensource.microsoft.com and join the Azure-samples org, once you're part of that (approval needed by Guy) then Aravind or myself can add you to the documentdb-samples-write team.

**Pull request merged**
